name: Cypress Tests on PR

on:
  pull_request:
    branches:
      - workout-log # Use your specific branch name for PRs

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # specify your Node.js version here

      - name: Install dependencies
        run: yarn install # use 'npm install' if you prefer npm
        working-directory: workout-log # Set working directory

      - name: Run Cypress tests
        run: npx cypress run # Run Cypress without additional flags
        working-directory: workout-log # Set working directory
