name: Cypress Tests on PR

on:
  pull_request:
    branches:
      - main # or the branch you want to track for PRs

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # specify your Node.js version here

      - name: Install dependencies
        run: yarn install # use 'npm install' if you prefer npm

      - name: Run Cypress tests
        run: npx cypress run --spec './*.cy.{js,jsx,ts,tsx}' # Adjust the glob pattern here
