name: Run Cypress Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cypress:
    runs-on: ubuntu-latest

    services:
      web:
        image: cypress/base:latest
        ports:
          - 4200:4200
        options: >-
          --health-cmd "curl --fail http://localhost:4200" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        env:
          CYPRESS_BASE_URL: http://localhost:4200

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run
